### ISSUE TITLE
Unable to pass local file path of . pkpass file 

### ISSUE THREAD

**Issue by devt259** [dev-family/react-native-wallet-manager#20]
Im trying to pass locally downloaded .pkpass file path as a param; But its only accepting remoteUrls.

Is there any way that we can add the local path of .pkpass file like the way [react-native-wallet](https://www.npmjs.com/package/react-native-wallet) is working.

It would be great if you add this 

Thanks

**Comment by mshekspirtt** [comment]
Fixed in version 0.0.7
