### ISSUE TITLE
Integration with Expo Go

### ISSUE THREAD

**Issue by moishinetzer** [dev-family/react-native-wallet-manager#22]
With the addition of native expo modules and expo plugins, would it be possible to integrate those options so that there is no need to run `expo run:ios` but `expo start --ios` which lets you open it from the Expo Go app and does not require a precompile step.

Thanks for the help this package is awesome!

**Comment by kacgrzes** [comment]
This is not possible. Expo Go cannot include external packages, but you can always use `expo-dev-client`.
