### ISSUE TITLE
Authenticating Web Requests

### ISSUE THREAD

**Issue by OwenMelbz** [dev-family/react-native-wallet-manager#23]
Hi,

We've got our backend which is set up able to generate the passes, however we need to have authentication in place to identify who the user is and if they have permission to download this pass.

The `addPassFromUrl` method just provides a URL, however doesn't allow us to apply any headers, POST payloads, etc to authenticate.

How would you suggest we do this?

Thanks

**Comment by mshekspirtt** [comment]
Hi, I think, you can find example in this article

https://www.nearform.com/insights/how-to-create-custom-apple-wallet-passes-with-react-native-and-fastify/
