### ISSUE TITLE
CardIdentifier

### ISSUE THREAD

**Issue by premsuthar42** [dev-family/react-native-wallet-manager#26]
"passTypeIdentifier" : "pass.com.apple.devpubs.example",
"passIdentifier" =  'pass.family.dev.stage.beerpoint-master'

how i get passIdentifier for check that pass already added in wallet?

**Comment by mshekspirtt** [comment]
check this [Issue](https://github.com/dev-family/react-native-wallet-manager/issues/3), pls

**Comment by anthlasserre** [comment]
Well, you can retrieve your pass type identifier within your .pass file.
To retrieve this information just follow these steps.

1. Download locally the `.pkpass`
2. Rename the extension to `.zip` and unzip it
3. Open the `pass.json` file within the folder you just unzip
4. There's a `passTypeIdentifier` value.

Here you can see the `pass.json` from the `.pkpass` file used in the example app.

![image](https://github.com/user-attachments/assets/0c95b50c-7c4d-41c3-9396-22bf5a3f79ba)
