### ISSUE TITLE
Add debit and credit card to wallet 

### ISSUE THREAD

**Issue by mrunalabhatt** [dev-family/react-native-wallet-manager#28]
Similar to passes, requesting to add support to add debit card or credit card to wallet. That would make this wallet manager with complete for all wallet features.

Or do we have any other react native or expo library which already achieve this then please refer.

**Comment by mshekspirtt** [comment]
Hi! Thank you for your suggestion. Currently, we don’t have this functionality implemented. Right now, we’re focusing on adding support for Google Wallet. After that, we may consider implementing the feature you requested.

**Comment by guidodipaolo** [comment]
+1
