### ISSUE TITLE
Support `.pkpasses` pass combination passes

### ISSUE THREAD

**Issue by dudeofawesome** [dev-family/react-native-wallet-manager#29]
When I attempt to add a `.pkpasses` file with `.addPassFromUrl()`, I get an error "`Error: The pass is invalid`".

Would it be possible to add support for adding `.pkpasses` files?

**Comment by mshekspirtt** [comment]
Unfortunately, the .pkpasses format is not officially supported for adding passes to Apple Wallet. Apple Wallet was initially designed to work with .pkpass files, which contain a single pass and are signed with a certificate issued by Apple. The .pkpasses format acts as a container for multiple .pkpass files, but, as noted in discussions on the [Apple Developer Forums](https://forums.developer.apple.com/forums/thread/739200), this format is not supported by most devices and versions of iOS for direct addition to Wallet.

**Comment by dudeofawesome** [comment]
Huh, that's odd that they're only supported in Safari. Thanks.

**Comment by sirmintoo** [comment]
> Unfortunately, the .pkpasses format is not officially supported for adding passes to Apple Wallet. Apple Wallet was initially designed to work with .pkpass files, which contain a single pass and are signed with a certificate issued by Apple. The .pkpasses format acts as a container for multiple .pkpass files, but, as noted in discussions on the [Apple Developer Forums](https://forums.developer.apple.com/forums/thread/739200), this format is not supported by most devices and versions of iOS for direct addition to Wallet.

can you please provide us the procress to download passes
