### ISSUE TITLE
hasPass and removePass return false (but pass already exists in Wallet)

### ISSUE THREAD

**Issue by khlor** [dev-family/react-native-wallet-manager#3]
Hi, hasPass and removePass don't seem to be working. They always return false. Have tried using my own pkpass as well the pkpasses in https://github.com/dev-family/react-native-wallet-manager/tree/main/example/resources/SamplePasses. Tried with and without serial number. Both funcs always return false no matter what. Any idea? Thank you

**Comment by yogesh048** [comment]
same things

**Comment by roni-castro-db** [comment]
It seems to work only using the [example app](https://github.com/dev-family/react-native-wallet-manager/tree/main/example), but I don't know why yet...

https://user-images.githubusercontent.com/95294257/191853661-44917a94-7c4b-447d-816e-5bd460e571b1.mov

**Comment by icrotz** [comment]
Hello, you can only manage pass kit after adding the "Wallet" capability on XCode. You can add pass without it but you can't manager them.

**Comment by mehdinourollah** [comment]
For anyone is wondering how to do so 

> Hello, you can only manage pass kit after adding the "Wallet" capability on XCode. You can add pass without it but you can't manage them.

for anyone like me wondering how to do so 
https://developer.apple.com/documentation/xcode/adding-capabilities-to-your-app

**Comment by Ajmal0197** [comment]
Found this tutorial helpful:

https://youtu.be/rJZdPoXHtzI?si=YW9JwYvLumvRB5Z-&t=249
