### ISSUE TITLE
NFC Features

### ISSUE THREAD

**Issue by cfontana0** [dev-family/react-native-wallet-manager#4]
Hello there 👋
Thanks for your hard work!

I'd like to know if I can use the NFC feature on the Apple Wallet when I add the pass to it.

For instance, can I add an access key to unlock a smart lock?

Thanks!

**Comment by mshekspirtt** [comment]
Hello.
I'm not sure, but you can try, in fact, the generation takes place on the backend, with the help of the library you only manage it.

**Comment by SohaibKtb** [comment]
@cfontana0 Hello, hope yor are doing well,

Were you able to unlock a smart lock using this library,
if yes, can you please provide some details 🙏
if no, did you manage to do it with other library?

thanks
