### ISSUE TITLE
Can it be implemented in an Expo App?

### ISSUE THREAD

**Issue by sirtok4** [dev-family/react-native-wallet-manager#5]
I'm using Expo to make my app and we need to add Apple and Samsung Wallet.

Is this package available for expo apps?

**Comment by cuddeford** [comment]
I am also interested in installing this with Expo.

**Comment by kyeap** [comment]
You can just implement this by following the instructions in the readMe, `podInstall` will be done autimatically when running `expo run`

**Comment by moishinetzer** [comment]
How do you add the entitlements, I can't get it to work

**Comment by renesass** [comment]
@moishinetzer did you get it running?

**Comment by moishinetzer** [comment]
Yup! This is what you need to add to your `app.json` to the `ios` section

```json
"entitlements": {
  "com.apple.developer.pass-type-identifiers": [
    "$(TeamIdentifierPrefix)*"
  ]
},
```
