### ISSUE TITLE
Has Pass and View Pass not working in TestFlight

### ISSUE THREAD

**Issue by sudippaudel793** [dev-family/react-native-wallet-manager#8]
I am able to add the pass however hasPass always show false in TestFlight, viewPass and removePass(always show false) are not working but is working fine in development mode. Shall I need to perform any extra setup to make it run in live or in TestFlight?

**Comment by dzolt** [comment]
Does it work on simulator for you? When I add a pass to the wallet on iOS simulator it adds the card correctly but when I check for it with hasPass it always returns false. Even the code from example folder it adds a card but then shows hasPass = false when I run the method.

**Comment by sudippaudel793** [comment]
Yes it works for me only in simulator and apple device in development mode. But not when in live.

**Comment by AbhinavJoosery** [comment]
Hi, I was also facing the same issue as @dzolt. I fixed it after adding the wallet capability on Xcode.

The following discussion helped me in fixing the issue:
https://github.com/dev-family/react-native-wallet-manager/issues/3

Other useful links:
https://developer.apple.com/documentation/xcode/adding-capabilities-to-your-app
https://developer.apple.com/documentation/xcode/configuring-wallet-support

**Comment by sudippaudel793** [comment]
Did it work in TestFlight too @AbhinavJoosery ?

**Comment by AbhinavJoosery** [comment]
@sudippaudel793 yes, it worked on TestFlight

**Comment by sudippaudel793** [comment]
I am not able to run it in Production mode. Can you please guide me @AbhinavJoosery ?

**Comment by sudippaudel793** [comment]
Working fine now, I missed one setup
